#kameplayer config option
#基本有効にしないでください
#ログが流れまくってパソコンが壊れても知りませんよ。
debug: false

#チャンク生成時の地下埋めるオプション
clearBlock:
  enable: false
  worlds:
  - dummy
  blockID:
  - 0
  - 5
  - 10
  - 11
  - 14
  - 15
  - 16
  - 21
  - 30
  - 37
  - 38
  - 39
  - 40
  - 47
  - 48
  - 49
  - 50
  - 52
  - 54
  - 56
  - 66
  - 73
  - 74
  - 85
  - 98
  - 101
  - 129
  - 175